gui:
  language: 'ja'
  timeFormat: 2006-01-02 15:04:05 -07:00
  nerdFontsVersion: '3'
  border: 'rounded'
  showIcons: true
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  editPreset: 'nvim'
